services:
  - type: web
    name: ikram-laravel-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: "Ikram System"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: file
      - key: APP_KEY
        value: "base64:7vG8S4v8g0uV1zT5mQ2wE4rT6yU8iO0pA1sD3fF5gH7="
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: ikram-postgres-db
          property: internalHost
      - key: DB_PORT
        fromDatabase:
          name: ikram-postgres-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: ikram-postgres-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: ikram-postgres-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ikram-postgres-db
          property: password

databases:
  - name: ikram-postgres-db
    plan: free
    databaseName: ikram_db
    user: ikram_user
