const vocabulary = {
  role: { admin: 'المدير العام', assistant_admin: 'مساعد المدير', reception: 'الاستقبال', staff: 'موظف', warehouse: 'المستودع', readonly: 'عرض فقط', driver: 'سائق تاريخي', delivery_driver: 'سائق تاريخي' },
  family: { poor: 'فقير', married: 'متزوج', single: 'أعزب', divorced: 'مطلقة', divorced_with_children: 'مطلقة مع أطفال', widow: 'أرملة', widower: 'أرمل', widow_with_orphans: 'أرملة تعول أيتامًا', abandoned: 'مهجورة', separated: 'منفصل' },
  housing: { rent: 'إيجار', own: 'ملك', owned: 'ملك', provided: 'سكن متاح', free: 'سكن مجاني', poor: 'متدني', average: 'متوسط', good: 'جيد' },
  beneficiary: { citizen: 'مواطن', resident: 'مقيم' },
  priority: { first_class: 'درجة أولى', class_first: 'درجة أولى', second_class: 'درجة ثانية', class_second: 'درجة ثانية', special_needs: 'ذوو الاحتياجات الخاصة', elderly: 'كبار السن', employee: 'عامل بالجمعية' },
  status: { in_delivery: 'جارٍ التوصيل', completed: 'مكتمل', active: 'نشط', suspended: 'موقوف', under_review: 'قيد المراجعة', confirmed: 'مؤكد', archived: 'مؤرشف', eligible: 'مؤهل', ineligible: 'غير مؤهل', pending: 'بانتظار الإرسال', queued: 'في قائمة الإرسال', retrying: 'بانتظار إعادة المحاولة', sending: 'جارٍ التواصل مع مزود الرسائل', sent: 'تم قبول الرسالة للإرسال', provider_accepted: 'قبل مزود الرسائل الطلب', delivered: 'تم التسليم المؤكد', failed: 'تعذر الإرسال', requested: 'تم طلب الإرسال', unknown: 'تحتاج نتيجة الإرسال إلى مراجعة', draft: 'مسودة', pending_approval: 'بانتظار الموافقة', approved: 'معتمد', reserved: 'تم حجز الأصناف', ready: 'جاهز للاستلام', assigned: 'تم إسناد التوصيل', cancelled: 'ملغي', rejected: 'مرفوض' },
  financialCategory: { A: 'الفئة الأولى', B: 'الفئة الثانية', C: 'الفئة الثالثة', D: 'الفئة الرابعة', E: 'الفئة الخامسة', a: 'الفئة الأولى', b: 'الفئة الثانية', c: 'الفئة الثالثة', d: 'الفئة الرابعة', e: 'الفئة الخامسة', eligible: 'مؤهل', ineligible: 'غير مؤهل' },
  scoreCategory: { A: 'الفئة الأولى', B: 'الفئة الثانية', C: 'الفئة الثالثة', D: 'الفئة الرابعة', E: 'الفئة الخامسة' },
  channel: { sms: 'رسالة نصية', email: 'بريد إلكتروني' },
  recipient: { beneficiary: 'مستفيد', staff: 'موظف', organization: 'جهة', driver: 'سائق', account: 'حساب' },
  fulfillment: { pickup: 'استلام مباشر', delivery: 'توصيل منزلي', direct_handover: 'استلام مباشر', home_delivery: 'توصيل منزلي' },
  providerError: { send_outcome_unknown: 'نتيجة الإرسال غير مؤكدة؛ يلزم التحقق قبل المحاولة', provider_timeout: 'انتهت مهلة مزود الرسائل', provider_rejected: 'رفض مزود الرسائل الطلب', payload_expired: 'انتهت صلاحية الرسالة', worker_timeout: 'انتهت مهلة الإرسال', provider_unavailable: 'مزود الرسائل غير متاح', provider_rate_limited: 'تم تجاوز حد الإرسال', provider_authentication: 'إعدادات اتصال مزود الرسائل تحتاج مراجعة' },
  token: { recipient_name: 'اسم المستلم', beneficiary_name: 'اسم المستفيد', staff_name: 'اسم الموظف', organization_name: 'اسم الجهة', fulfillment_method: 'طريقة التسليم', delivery_date: 'تاريخ التسليم', verification_code: 'رمز الاستلام', association_name: 'اسم الجمعية', pickup_location_name: 'اسم موقع الاستلام', pickup_location_url: 'رابط موقع الاستلام', driver_name: 'اسم السائق', temporary_driver_link: 'رابط السائق الآمن', link_expiry: 'انتهاء صلاحية الرابط', user_name: 'اسم المستخدم', reset_link: 'رابط استعادة الحساب', reset_expiry: 'انتهاء صلاحية الاستعادة', reset_code: 'رمز التحقق', expiry_minutes: 'مدة الصلاحية بالدقائق' },
};
export function displayLabel(category, value) { return vocabulary[category]?.[value] || 'غير محدد'; }
export function templateDisplay(text) { return String(text || '').replace(/\{([a-z_]+)\}/g, (_, key) => '‹' + displayLabel('token', key) + '›'); }
export function templateStorage(text, allowed = []) { return allowed.reduce((result, key) => result.split('‹' + displayLabel('token', key) + '›').join('{' + key + '}'), text); }
